#!/bin/sh

CONF_FILE="etc/system.conf"

if [ -d "/usr/yi-hack-v4" ]; then
        YI_HACK_V4_PREFIX="/usr/yi-hack-v4"
elif [ -d "/home/yi-hack-v4" ]; then
        YI_HACK_V4_PREFIX="/home/yi-hack-v4"
fi

get_config()
{
	key=$1
	grep $1 $YI_HACK_V4_PREFIX/$CONF_FILE | cut -d "=" -f2
}
                
if [[ $(get_config PROXYCHAINSNG) == "yes" ]] ; then
	$YI_HACK_V4_PREFIX/bin/proxychains4 ./cloudAPI_real "$@"
else
	./cloudAPI_real "$@"
fi

