#!/bin/sh

mkdir /dev/pts
mount -t devpts devpts /dev/pts

mkdir -p /dev/.udev
udevd --daemon
udevadm trigger
mount -t jffs2 /dev/mtdblock5 /home

/home/yi-hack-v4/script/system_init.sh
/home/base/init.sh

